spring:
  datasource:
    url: jdbc:h2:mem:~/db
    username: admin
    password: password
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      cache:
        period: 0
      static-locations: file:src/main/resources/static/